#Dockerfile for building of AIAP_XGBoostModel

FROM mysql:5.7
MAINTAINER Kuan Wee <kuan.wee@hotmail.com>

# Add a database
ENV MYSQL_DATABASE aiap_traffic

# Add the content of the sql-scripts/ directory to your image
# All scripts in docker-entrypoint-initdb.d/ are automatically
# executed during container startup
COPY ./sql-scripts/ /docker-entrypoint-initdb.d/